### ISSUE TITLE
How to personalized Utilization Labels (tspan)

### ISSUE THREAD

**Issue by kibwashere** [otm/networkmap.js#7]
First of all, good job for this amazing tool, it is very useful for me !

I would like to know how I can edit the tspan labels. For the moment there are only your random values when I check 'Utilization Labels' to 'Enabled' in the 'Settings'.

Is it possible to insert a value into a tspan via the .json config ?
For example : 
"tspan" : "my_value"

Thanks in advance :)

**Comment by otm** [comment]
Sorry for the slow reply, the github notice downed in my inbox. Short answer, yes you do that by registring your own datasource. That is the function that will be called when the networkmap will be refreshed. That will give you a chance to call your backend to fetch data and transform it. The utilization will be picked up by the link and displayed. Check the link bellow for an example function
https://github.com/otm/networkmap.js/blob/master/src/datasource.js#L32

When you have your data source you use need to load it by:
```map = new networkMap.Graph('example2', {datasource: 'example'}).load('assets/weathermap/example2.json');```

Please let me know if I missed something.

**Comment by kibwashere** [comment]
So I added an ajax request in this function. I get a value for each link from the json file and then I request my data source from another website with the ajax function.
And it works perfectly, thank you :­D !
